services:
  app:
    build: .
    image: docker.ks2.nmt.com.hk/audio-service:jetson-r36.4.0
    volumes:
      - .local:/home/app/.local
    network_mode: host
    restart: unless-stopped
    devices:
      - /dev/snd
      - /dev/bus/usb
    env_file:
      - .env
