#!/usr/bin/env node
/**
 * Cleanup Test Pages for Friday Web Portal
 * 
 * This script removes test pages generated by generate-test-pages.ts.
 * Run: npm run test:cleanup
 */

import fs from 'fs';
import path from 'path';
import 'dotenv/config';

// Configuration from environment
const WEB_PORTAL_ROOT = process.env.WEB_PORTAL_ROOT || './web_portal';

// Test user ID (must match generate-test-pages.ts)
const TEST_USER_ID = 'test-user-001';

interface CleanupResult {
    removedDirs: string[];
    removedFiles: string[];
    errors: string[];
}

function cleanupTestPages(): CleanupResult {
    const result: CleanupResult = {
        removedDirs: [],
        removedFiles: [],
        errors: []
    };
    
    console.log('🧹 Cleaning up test pages...\n');
    console.log(`Web Portal Root: ${WEB_PORTAL_ROOT}`);
    console.log(`Test User ID: ${TEST_USER_ID}\n`);
    
    const testUserDir = path.join(WEB_PORTAL_ROOT, TEST_USER_ID);
    
    if (!fs.existsSync(testUserDir)) {
        console.log('No test pages found to clean up.');
        return result;
    }
    
    // Read all page directories
    const entries = fs.readdirSync(testUserDir, { withFileTypes: true });
    
    for (const entry of entries) {
        const fullPath = path.join(testUserDir, entry.name);
        
        try {
            if (entry.isDirectory()) {
                // Remove directory and all contents
                fs.rmSync(fullPath, { recursive: true, force: true });
                result.removedDirs.push(entry.name);
                console.log(`✅ Removed directory: ${entry.name}`);
            } else if (entry.name === 'manifest.json') {
                // Remove manifest file
                fs.unlinkSync(fullPath);
                result.removedFiles.push(entry.name);
                console.log(`✅ Removed file: ${entry.name}`);
            }
        } catch (err) {
            const errorMsg = `Failed to remove ${entry.name}: ${err}`;
            result.errors.push(errorMsg);
            console.error(`❌ ${errorMsg}`);
        }
    }
    
    // Try to remove the test user directory if empty
    try {
        const remaining = fs.readdirSync(testUserDir);
        if (remaining.length === 0) {
            fs.rmdirSync(testUserDir);
            console.log(`\n✅ Removed test user directory: ${TEST_USER_ID}`);
        }
    } catch (err) {
        // Directory not empty or other error - not critical
    }
    
    console.log('\n--- Cleanup Summary ---');
    console.log(`Directories removed: ${result.removedDirs.length}`);
    console.log(`Files removed: ${result.removedFiles.length}`);
    
    if (result.errors.length > 0) {
        console.log(`Errors: ${result.errors.length}`);
        result.errors.forEach(e => console.log(`  - ${e}`));
    }
    
    return result;
}

// Run the cleanup
cleanupTestPages();